In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import platform
import matplotlib
import shap
import joblib
import tensorflow as tf
from lightgbm import LGBMRegressor
from xgboost import plot_importance
from xgboost import XGBClassifier
from xgboost import XGBRegressor
from math import sqrt
from keras.callbacks import ModelCheckpoint
from keras.callbacks import EarlyStopping
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, LSTM, SimpleRNN, Dropout
from tensorflow.keras import layers
from imblearn.over_sampling import SMOTE
from sklearn import svm
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score, confusion_matrix, mean_squared_error, mean_absolute_error, r2_score
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import VotingClassifier, RandomForestClassifier, RandomForestRegressor, AdaBoostRegressor, GradientBoostingRegressor
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from matplotlib import font_manager, rc
path = "c:/Windows/Fonts/malgun.ttf"
if platform.system() == 'Darwin':
    rc('font', family='AppleGothic')
elif platform.system() == 'Windows':
    font_name = font_manager.FontProperties(fname=path).get_name()
    rc('font', family=font_name)
else:
    print('Unknown system... sorry~~~~')

C:\Anaconda3\lib\site-packages\statsmodels\tools\_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm
Using TensorFlow backend.

# 봄

In [185]:
data봄 = pd.read_excel("C:/Users/PC/Desktop/봄.xlsx")
data봄

,id,관리기관,단지명,근로자수,근로손실일,중대재해유무,그리드 내 총 기업 수,매출액,부채비율,재해율,...,중업종분류_목재및종이제품제조업,중업종분류_수제품및기타제품제조업,중업종분류_식료품제조업,중업종분류_시설관리및사업지원서비스업,중업종분류_전기 가스 증기및수도사업,중업종분류_의약품 화장품 연탄 석유제품제조업,중업종분류_도소매 음식 숙박업,중업종분류_육상및수상운수업,중업종분류_통신업,중업종분류_기타의각종사업
0,17090775,한국산업단지공단 울산지역본부,울산미포국가산업단지,14284.0,306.5,True,5,2.999488e+09,157.4180,0.792495,...,0,0,0,0,0,0,0,0,0,0
1,12823536,한국산업단지공단 경남지역본부,창원국가산업단지,4337.0,283.0,True,4,3.708635e+09,187.8264,0.461148,...,0,0,0,0,2,0,0,0,0,0
2,16959388,한국산업단지공단 울산지역본부,울산미포국가산업단지,2997.0,276.0,True,1,2.857835e+09,53.0124,2.369036,...,0,0,0,0,0,0,0,0,0,0
3,13326267,한국산업단지공단 경남지역본부,창원국가산업단지,2039.0,258.0,True,4,8.497518e+09,223.4079,0.846003,...,0,0,0,0,2,0,0,0,0,0
4,3166196,한국산업단지공단 경기지역본부 시화지사,시화국가산업단지,350.0,84.0,True,1,4.531108e+08,141.4237,19.428571,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1612,3389035,한국산업단지공단 경기지역본부,반월국가산업단지,21.0,43.0,False,3,1.403320e+07,62.6035,1.587302,...,0,0,0,0,0,0,0,0,0,0
1613,11777547,한국산업단지공단 대구지역본부 달성사무소,달성2차일반산업단지,10.0,177.0,False,3,4.250820e+06,454.0223,3.333333,...,0,0,1,0,0,0,0,0,0,0
1614,2863330,한국산업단지공단 인천지역본부,남동국가산업단지,22.0,50.0,False,7,3.686506e+06,371.4939,0.649351,...,0,0,0,0,0,0,0,0,0,0
1615,2863328,한국산업단지공단 인천지역본부,남동국가산업단지,60.0,125.0,False,7,1.898501e+07,113.8615,0.238095,...,0,0,0,0,0,0,0,0,0,0
1616,3377613,한국산업단지공단 경기지역본부,반월국가산업단지,19.0,241.0,True,2,4.123017e+06,-489.5588,2.631579,...,0,0,0,0,0,0,0,0,0,0

In [186]:
data봄[data봄["재해율"].isnull()]

,id,관리기관,단지명,근로자수,근로손실일,중대재해유무,그리드 내 총 기업 수,매출액,부채비율,재해율,...,중업종분류_목재및종이제품제조업,중업종분류_수제품및기타제품제조업,중업종분류_식료품제조업,중업종분류_시설관리및사업지원서비스업,중업종분류_전기 가스 증기및수도사업,중업종분류_의약품 화장품 연탄 석유제품제조업,중업종분류_도소매 음식 숙박업,중업종분류_육상및수상운수업,중업종분류_통신업,중업종분류_기타의각종사업
703,1512279,한국산업단지공단 전남지역본부 대불지사,대불국가산업단지,0.0,1023.0,False,3,5483642.0,151.5790,NaN,...,0,0,0,0,0,0,0,0,0,0
813,2988996,한국산업단지공단 인천지역본부,남동국가산업단지,0.0,175.0,False,13,1289822.0,90.7389,NaN,...,0,1,0,0,0,0,0,0,0,0

In [187]:
data봄.중대재해유무 = data봄.중대재해유무.astype("int")

In [188]:
data봄.drop(columns = data봄.iloc[:, 10:71], inplace = True)

In [189]:
data봄.dropna(inplace = True)

In [190]:
X봄 = data봄.drop(columns = ["id", "관리기관", "단지명", "근로손실일", "재해율"])
y봄 = data봄["재해율"]

In [191]:
scaler = MinMaxScaler()

X봄 = pd.DataFrame(scaler.fit_transform(X봄), columns = X봄.columns)

In [192]:
model_gbm봄 = joblib.load('model_gbm_봄.pkl')

In [193]:
model_gbm_pred봄 = model_gbm봄.predict(X봄)

gbm_rmse봄 = mean_squared_error(model_gbm_pred봄, y봄, squared = False)

print("rmse :", gbm_rmse봄)
print("r2_score :", r2_score(y봄, model_gbm_pred봄))

rmse : 1.6003238836233855
r2_score : 0.9065970456447944

In [194]:
data봄 = data봄[["id", "관리기관", "단지명", "그리드 내 총 기업 수"]]
data봄

            id                   관리기관         단지명  그리드 내 총 기업 수
0     17090775        한국산업단지공단 울산지역본부  울산미포국가산업단지             5
1     12823536        한국산업단지공단 경남지역본부    창원국가산업단지             4
2     16959388        한국산업단지공단 울산지역본부  울산미포국가산업단지             1
3     13326267        한국산업단지공단 경남지역본부    창원국가산업단지             4
4      3166196   한국산업단지공단 경기지역본부 시화지사    시화국가산업단지             1
...        ...                    ...         ...           ...
1612   3389035        한국산업단지공단 경기지역본부    반월국가산업단지             3
1613  11777547  한국산업단지공단 대구지역본부 달성사무소  달성2차일반산업단지             3
1614   2863330        한국산업단지공단 인천지역본부    남동국가산업단지             7
1615   2863328        한국산업단지공단 인천지역본부    남동국가산업단지             7
1616   3377613        한국산업단지공단 경기지역본부    반월국가산업단지             2

[1615 rows x 4 columns]

In [195]:
data봄["재해율"] = model_gbm_pred봄

A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [196]:
data봄.to_excel("C:/Users/PC/Desktop/봄_재해율.xlsx", index = False)

# 여름

In [197]:
data여름 = pd.read_excel("C:/Users/PC/Desktop/여름.xlsx")
data여름

,id,관리기관,단지명,근로자수,근로손실일,중대재해유무,그리드 내 총 기업 수,매출액,부채비율,재해율,...,중업종분류_목재및종이제품제조업,중업종분류_수제품및기타제품제조업,중업종분류_식료품제조업,중업종분류_시설관리및사업지원서비스업,중업종분류_전기 가스 증기및수도사업,중업종분류_의약품 화장품 연탄 석유제품제조업,중업종분류_도소매 음식 숙박업,중업종분류_육상및수상운수업,중업종분류_통신업,중업종분류_기타의각종사업
0,17090775,한국산업단지공단 울산지역본부,울산미포국가산업단지,14284.0,289.5,True,5,5.456668e+09,157.4180,0.786894,...,0,0,0,0,0,0,0,0,0,0
1,12823536,한국산업단지공단 경남지역본부,창원국가산업단지,4771.0,280.0,True,4,3.708635e+09,172.7770,0.351079,...,0,0,0,0,2,0,0,0,0,0
2,16959388,한국산업단지공단 울산지역본부,울산미포국가산업단지,2997.0,294.0,True,1,2.780781e+09,53.0124,1.868535,...,0,0,0,0,0,0,0,0,0,0
3,13326267,한국산업단지공단 경남지역본부,창원국가산업단지,2039.0,230.5,True,4,8.497518e+09,223.4079,0.662089,...,0,0,0,0,2,0,0,0,0,0
4,3166196,한국산업단지공단 경기지역본부 시화지사,시화국가산업단지,367.0,166.0,True,1,4.213202e+08,149.3217,12.261580,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1660,3137645,한국산업단지공단 경기지역본부 시화지사,시화국가산업단지,5.0,49.0,False,7,5.428970e+05,192.0247,2.857143,...,1,0,0,0,0,0,0,0,0,0
1661,3137644,한국산업단지공단 경기지역본부,반월국가산업단지,4.0,124.0,False,5,5.579085e+05,196.6834,5.000000,...,0,0,0,0,0,0,0,0,0,0
1662,3137646,한국산업단지공단 경기지역본부 시화지사,시화국가산업단지,9.0,335.0,True,1,5.585063e+06,117.6545,11.111111,...,0,0,0,0,0,0,0,0,0,0
1663,3137642,한국산업단지공단 경기지역본부 시화지사,시화국가산업단지,21.0,47.0,False,13,5.564900e+06,204.5394,0.366300,...,0,0,0,0,0,0,0,0,0,0
1664,16879367,한국산업단지공단 울산지역본부,울산미포국가산업단지,2.0,42.0,False,2,5.579085e+05,196.6834,25.000000,...,0,0,0,0,0,0,0,0,0,0

In [198]:
data여름[data여름["재해율"].isnull()]

,id,관리기관,단지명,근로자수,근로손실일,중대재해유무,그리드 내 총 기업 수,매출액,부채비율,재해율,...,중업종분류_목재및종이제품제조업,중업종분류_수제품및기타제품제조업,중업종분류_식료품제조업,중업종분류_시설관리및사업지원서비스업,중업종분류_전기 가스 증기및수도사업,중업종분류_의약품 화장품 연탄 석유제품제조업,중업종분류_도소매 음식 숙박업,중업종분류_육상및수상운수업,중업종분류_통신업,중업종분류_기타의각종사업
435,1500852,한국산업단지공단 전남지역본부 대불지사,대불국가산업단지,0.0,52.5,False,2,1025096.5,1089.70355,NaN,...,0,0,0,0,1,0,0,0,0,0
504,3023373,한국산업단지공단 경기지역본부 시화지사,시화국가산업단지,0.0,29.5,False,15,557908.5,196.68340,NaN,...,2,0,0,0,0,0,0,0,0,0
761,2983284,한국산업단지공단 인천지역본부,남동국가산업단지,0.0,177.0,False,17,557908.5,196.68340,NaN,...,1,0,0,0,0,0,0,0,0,0
903,3286200,한국산업단지공단 경기지역본부,반월국가산업단지,0.0,99.0,False,4,557908.5,196.68340,NaN,...,0,0,0,0,0,0,0,0,0,0
1207,3223335,한국산업단지공단 경기지역본부,반월국가산업단지,0.0,87.0,False,5,557908.5,196.68340,NaN,...,0,0,0,0,0,1,0,0,0,0
1245,2954796,한국산업단지공단 시화지사 시화MTV사무소,시화멀티테크노밸리,0.0,270.0,True,1,290717.0,79.47250,NaN,...,0,0,0,0,0,0,0,0,0,0
1592,3143353,한국산업단지공단 경기지역본부 시화지사,시화국가산업단지,0.0,273.0,True,102,557908.5,196.68340,NaN,...,0,0,3,0,0,0,0,0,0,0

In [199]:
data여름.중대재해유무 = data여름.중대재해유무.astype("int")

In [200]:
data여름.drop(columns = data여름.iloc[:, 10:71], inplace = True)

In [201]:
data여름.dropna(inplace = True)

In [202]:
X여름 = data여름.drop(columns = ["id", "관리기관", "단지명", "근로손실일", "재해율"])
y여름 = data여름["재해율"]

In [203]:
scaler = MinMaxScaler()

X여름 = pd.DataFrame(scaler.fit_transform(X여름), columns = X여름.columns)

In [204]:
model_rf여름 = joblib.load('model_rf_여름.pkl')

In [205]:
model_rf_pred여름 = model_rf여름.predict(X여름)

rf_rmse여름 = mean_squared_error(model_rf_pred여름, y여름, squared = False)

print("rmse :", rf_rmse여름)
print("r2_score :", r2_score(y여름, model_rf_pred여름))

rmse : 1.9045394129123823
r2_score : 0.9237972469987916

In [206]:
data여름 = data여름[["id", "관리기관", "단지명", "그리드 내 총 기업 수"]]
data여름

            id                  관리기관         단지명  그리드 내 총 기업 수
0     17090775       한국산업단지공단 울산지역본부  울산미포국가산업단지             5
1     12823536       한국산업단지공단 경남지역본부    창원국가산업단지             4
2     16959388       한국산업단지공단 울산지역본부  울산미포국가산업단지             1
3     13326267       한국산업단지공단 경남지역본부    창원국가산업단지             4
4      3166196  한국산업단지공단 경기지역본부 시화지사    시화국가산업단지             1
...        ...                   ...         ...           ...
1660   3137645  한국산업단지공단 경기지역본부 시화지사    시화국가산업단지             7
1661   3137644       한국산업단지공단 경기지역본부    반월국가산업단지             5
1662   3137646  한국산업단지공단 경기지역본부 시화지사    시화국가산업단지             1
1663   3137642  한국산업단지공단 경기지역본부 시화지사    시화국가산업단지            13
1664  16879367       한국산업단지공단 울산지역본부  울산미포국가산업단지             2

[1658 rows x 4 columns]

In [207]:
data여름["재해율"] = model_rf_pred여름

A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [208]:
data여름.to_excel("C:/Users/PC/Desktop/여름_재해율.xlsx", index = False)

# 가을

In [209]:
data가을 = pd.read_excel("C:/Users/PC/Desktop/가을.xlsx")
data가을

,id,관리기관,단지명,근로자수,근로손실일,중대재해유무,그리드 내 총 기업 수,매출액,부채비율,재해율,...,중업종분류_목재및종이제품제조업,중업종분류_수제품및기타제품제조업,중업종분류_식료품제조업,중업종분류_시설관리및사업지원서비스업,중업종분류_전기 가스 증기및수도사업,중업종분류_의약품 화장품 연탄 석유제품제조업,중업종분류_도소매 음식 숙박업,중업종분류_육상및수상운수업,중업종분류_통신업,중업종분류_기타의각종사업
0,17090775,한국산업단지공단 울산지역본부,울산미포국가산업단지,12992.0,373.0,True,5,5.456668e+09,157.4180,0.885160,...,0,0,0,0,0,0,0,0,0,0
1,12823536,한국산업단지공단 경남지역본부,창원국가산업단지,4771.0,201.5,True,4,4.101664e+09,172.7770,0.314399,...,0,0,0,0,2,0,0,0,0,0
2,3166196,한국산업단지공단 경기지역본부 시화지사,시화국가산업단지,379.0,56.5,True,1,4.426323e+08,149.3217,12.664908,...,0,0,0,0,0,0,0,0,0,0
3,16959388,한국산업단지공단 울산지역본부,울산미포국가산업단지,2940.0,387.0,True,1,2.780781e+09,52.9558,1.224490,...,0,0,0,0,0,0,0,0,0,0
4,13326267,한국산업단지공단 경남지역본부,창원국가산업단지,2039.0,353.5,True,4,8.497518e+09,223.4079,0.367827,...,0,0,0,0,2,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1558,3154772,한국산업단지공단 경기지역본부 시화지사,시화국가산업단지,13.0,56.0,False,9,3.742934e+06,404.1093,0.854701,...,0,0,0,0,0,0,0,0,0,0
1559,3154764,한국산업단지공단 경기지역본부 시화지사,시화국가산업단지,40.0,43.0,False,7,6.390193e+06,28.4231,0.357143,...,0,0,0,0,0,0,0,0,0,0
1560,11542822,한국산업단지공단 경북지역본부,구미국가산업단지,1.0,173.0,False,5,9.928310e+05,50.5371,20.000000,...,0,0,0,0,0,0,0,0,0,0
1561,11542790,한국산업단지공단 경북지역본부,구미국가산업단지,139.0,106.0,False,3,1.069881e+07,51.6222,0.239808,...,0,0,0,0,0,0,0,0,0,0
1562,16616605,한국산업단지공단 울산지역본부,울산미포국가산업단지,37.0,129.0,False,4,3.730933e+06,164.3668,0.675676,...,0,0,0,0,0,0,0,0,0,0

In [210]:
data가을[data가을["재해율"].isnull()]

,id,관리기관,단지명,근로자수,근로손실일,중대재해유무,그리드 내 총 기업 수,매출액,부채비율,재해율,...,중업종분류_목재및종이제품제조업,중업종분류_수제품및기타제품제조업,중업종분류_식료품제조업,중업종분류_시설관리및사업지원서비스업,중업종분류_전기 가스 증기및수도사업,중업종분류_의약품 화장품 연탄 석유제품제조업,중업종분류_도소매 음식 숙박업,중업종분류_육상및수상운수업,중업종분류_통신업,중업종분류_기타의각종사업
118,3103366,한국산업단지공단 경기지역본부 시화지사,시화국가산업단지,0.0,77.0,False,7,8.292318e+06,333.6695,NaN,...,0,0,0,0,0,0,0,0,0,0
426,3389016,한국산업단지공단 경기지역본부,반월국가산업단지,0.0,3868.5,True,19,1.039811e+09,48.2981,NaN,...,0,0,0,0,0,0,0,0,0,0
605,3086228,한국산업단지공단 경기지역본부 시화지사,시화국가산업단지,0.0,55.0,False,24,7.862070e+05,4.7089,NaN,...,0,0,0,0,0,0,0,0,0,0
645,2983284,한국산업단지공단 인천지역본부,남동국가산업단지,0.0,84.0,False,17,1.868660e+05,196.6834,NaN,...,1,0,0,0,0,0,0,0,0,0
686,3000535,한국산업단지공단 경기지역본부 시화지사,시화국가산업단지,0.0,84.0,False,5,1.376015e+06,1235.6246,NaN,...,0,0,0,0,0,0,0,0,0,0
999,2960521,한국산업단지공단 경기지역본부 시화지사,시화국가산업단지,0.0,141.0,False,18,8.189300e+05,460.3301,NaN,...,1,0,0,0,0,0,0,0,0,0
1342,3126220,한국산업단지공단 경기지역본부 시화지사,시화국가산업단지,0.0,28.0,False,18,9.208200e+05,457.4561,NaN,...,0,0,1,0,0,0,0,0,0,0

In [211]:
data가을.중대재해유무 = data가을.중대재해유무.astype("int")

In [212]:
data가을.drop(columns = data가을.iloc[:, 10:71], inplace = True)

In [213]:
data가을.dropna(inplace = True)

In [214]:
X가을 = data가을.drop(columns = ["id", "관리기관", "단지명", "근로손실일", "재해율"])
y가을 = data가을["재해율"]

In [215]:
scaler = MinMaxScaler()

X가을 = pd.DataFrame(scaler.fit_transform(X가을), columns = X가을.columns)

In [216]:
model_gbm가을 = joblib.load('model_gbm_가을.pkl')

In [217]:
model_gbm_pred가을 = model_gbm가을.predict(X가을)

gbm_rmse가을 = mean_squared_error(model_gbm_pred가을, y가을, squared = False)

print("rmse :", gbm_rmse가을)
print("r2_score :", r2_score(y가을, model_gbm_pred가을))

rmse : 1.480242660954895
r2_score : 0.9584670431426501

In [218]:
data가을 = data가을[["id", "관리기관", "단지명", "그리드 내 총 기업 수"]]
data가을

            id                  관리기관         단지명  그리드 내 총 기업 수
0     17090775       한국산업단지공단 울산지역본부  울산미포국가산업단지             5
1     12823536       한국산업단지공단 경남지역본부    창원국가산업단지             4
2      3166196  한국산업단지공단 경기지역본부 시화지사    시화국가산업단지             1
3     16959388       한국산업단지공단 울산지역본부  울산미포국가산업단지             1
4     13326267       한국산업단지공단 경남지역본부    창원국가산업단지             4
...        ...                   ...         ...           ...
1558   3154772  한국산업단지공단 경기지역본부 시화지사    시화국가산업단지             9
1559   3154764  한국산업단지공단 경기지역본부 시화지사    시화국가산업단지             7
1560  11542822       한국산업단지공단 경북지역본부    구미국가산업단지             5
1561  11542790       한국산업단지공단 경북지역본부    구미국가산업단지             3
1562  16616605       한국산업단지공단 울산지역본부  울산미포국가산업단지             4

[1556 rows x 4 columns]

In [219]:
data가을["재해율"] = model_gbm_pred가을

A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [220]:
data가을.to_excel("C:/Users/PC/Desktop/가을_재해율.xlsx", index = False)

# 겨울

In [221]:
data겨울 = pd.read_excel("C:/Users/PC/Desktop/겨울.xlsx")
data겨울

,id,관리기관,단지명,근로자수,근로손실일,중대재해유무,그리드 내 총 기업 수,매출액,부채비율,재해율,...,중업종분류_목재및종이제품제조업,중업종분류_수제품및기타제품제조업,중업종분류_식료품제조업,중업종분류_시설관리및사업지원서비스업,중업종분류_전기 가스 증기및수도사업,중업종분류_의약품 화장품 연탄 석유제품제조업,중업종분류_도소매 음식 숙박업,중업종분류_육상및수상운수업,중업종분류_통신업,중업종분류_기타의각종사업
0,17090775,한국산업단지공단 울산지역본부,울산미포국가산업단지,14284.0,401.0,True,5,5.456668e+09,157.4180,0.828899,...,0,0,0,0,0,0,0,0,0,0
1,12823536,한국산업단지공단 경남지역본부,창원국가산업단지,4771.0,373.0,True,4,4.101664e+09,187.8264,0.440159,...,0,0,0,0,2,0,0,0,0,0
2,16959388,한국산업단지공단 울산지역본부,울산미포국가산업단지,2940.0,401.0,True,1,2.780781e+09,53.0124,2.687075,...,0,0,0,0,0,0,0,0,0,0
3,3166196,한국산업단지공단 경기지역본부 시화지사,시화국가산업단지,367.0,85.5,True,1,4.531108e+08,141.4237,14.713896,...,0,0,0,0,0,0,0,0,0,0
4,13326267,한국산업단지공단 경남지역본부,창원국가산업단지,2205.0,351.0,True,4,8.497518e+09,178.4200,0.510204,...,0,0,0,0,2,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1496,2937583,한국산업단지공단 인천지역본부,남동국가산업단지,44.0,77.0,False,101,8.582188e+07,288.8395,0.022502,...,4,0,3,1,0,0,0,0,0,0
1497,3120505,한국산업단지공단 경기지역본부 시화지사,시화국가산업단지,37.0,185.0,False,9,6.151679e+06,413.4459,0.300300,...,0,0,0,0,0,0,0,0,0,0
1498,3120511,한국산업단지공단 경기지역본부 시화지사,시화국가산업단지,45.0,21.0,False,5,8.477175e+06,211.2631,0.444444,...,3,0,0,0,0,0,0,0,0,0
1499,13160581,한국산업단지공단 경남지역본부,창원국가산업단지,56.0,101.0,False,4,2.236227e+07,113.6255,0.446429,...,0,0,0,0,0,0,0,0,0,0
1500,16879367,한국산업단지공단 울산지역본부,울산미포국가산업단지,97.0,603.0,False,2,2.155992e+09,-832.2838,0.515464,...,0,0,0,0,0,0,0,0,0,0

In [222]:
data겨울[data겨울["재해율"].isnull()]

,id,관리기관,단지명,근로자수,근로손실일,중대재해유무,그리드 내 총 기업 수,매출액,부채비율,재해율,...,중업종분류_목재및종이제품제조업,중업종분류_수제품및기타제품제조업,중업종분류_식료품제조업,중업종분류_시설관리및사업지원서비스업,중업종분류_전기 가스 증기및수도사업,중업종분류_의약품 화장품 연탄 석유제품제조업,중업종분류_도소매 음식 숙박업,중업종분류_육상및수상운수업,중업종분류_통신업,중업종분류_기타의각종사업
602,3086227,한국산업단지공단 경기지역본부 시화지사,시화국가산업단지,0.0,246.0,True,15,908108.0,546.3261,NaN,...,0,0,0,0,0,0,0,0,0,0
717,3354746,한국산업단지공단 경기지역본부 시화지사,시화국가산업단지,0.0,69.0,False,10,557908.5,196.6834,NaN,...,0,0,0,0,0,0,0,0,0,0
897,3057659,한국산업단지공단 경기지역본부 시화지사,시화국가산업단지,0.0,361.0,True,11,203054.0,692.6152,NaN,...,0,0,0,0,0,0,0,0,0,0
916,3063351,한국산업단지공단 경기지역본부 시화지사,시화국가산업단지,0.0,7500.0,True,46,453725.0,182.4319,NaN,...,0,0,0,0,1,0,0,0,0,0

In [223]:
data겨울.중대재해유무 = data겨울.중대재해유무.astype("int")

In [224]:
data겨울.drop(columns = data겨울.iloc[:, 10:71], inplace = True)

In [225]:
data겨울.dropna(inplace = True)

In [226]:
X겨울 = data겨울.drop(columns = ["id", "관리기관", "단지명", "근로손실일", "재해율"])
y겨울 = data겨울["재해율"]

In [227]:
scaler = MinMaxScaler()

X겨울 = pd.DataFrame(scaler.fit_transform(X겨울), columns = X겨울.columns)

In [228]:
model_lgb겨울 = joblib.load('model_lgb_겨울.pkl')

In [229]:
model_lgb_pred겨울 = model_lgb겨울.predict(X겨울)

lgb_rmse겨울 = mean_squared_error(model_lgb_pred겨울, y겨울, squared = False)

print("rmse :", lgb_rmse겨울)
print("r2_score :", r2_score(y겨울, model_lgb_pred겨울))

rmse : 2.449893220566615
r2_score : 0.6792573428208823

In [230]:
data겨울 = data겨울[["id", "관리기관", "단지명", "그리드 내 총 기업 수"]]
data겨울

            id                  관리기관         단지명  그리드 내 총 기업 수
0     17090775       한국산업단지공단 울산지역본부  울산미포국가산업단지             5
1     12823536       한국산업단지공단 경남지역본부    창원국가산업단지             4
2     16959388       한국산업단지공단 울산지역본부  울산미포국가산업단지             1
3      3166196  한국산업단지공단 경기지역본부 시화지사    시화국가산업단지             1
4     13326267       한국산업단지공단 경남지역본부    창원국가산업단지             4
...        ...                   ...         ...           ...
1496   2937583       한국산업단지공단 인천지역본부    남동국가산업단지           101
1497   3120505  한국산업단지공단 경기지역본부 시화지사    시화국가산업단지             9
1498   3120511  한국산업단지공단 경기지역본부 시화지사    시화국가산업단지             5
1499  13160581       한국산업단지공단 경남지역본부    창원국가산업단지             4
1500  16879367       한국산업단지공단 울산지역본부  울산미포국가산업단지             2

[1497 rows x 4 columns]

In [231]:
data겨울["재해율"] = model_lgb_pred겨울

A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [232]:
data겨울.to_excel("C:/Users/PC/Desktop/겨울_재해율.xlsx", index = False)

In [244]:
data겨울.describe()

                 id  그리드 내 총 기업 수          재해율
count  1.497000e+03   1497.000000  1497.000000
mean   6.564010e+06     16.991984     2.203280
std    5.157268e+06     48.647495     3.148884
min    1.432285e+06      1.000000    -0.603732
25%    3.000494e+06      2.000000     0.732781
50%    3.257610e+06      5.000000     1.252838
75%    1.280066e+07     12.000000     2.487003
max    1.709078e+07    767.000000    26.984216